//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int id { get; set; }
        public string type { get; set; }
        public int quantity { get; set; }
        public Nullable<int> request_id { get; set; }
    
        public virtual request request { get; set; }
    }
}
