//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zero_hungerEntities : DbContext
    {
        public zero_hungerEntities()
            : base("name=zero_hungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<restaurant> restaurants { get; set; }
    }
}
